defaults:
  - cuda: default
  - data: nerf_synthetic
  - network: instant_nerf
  - objective: nerf
  - train_params: nerf
  - scene: multires_hash
  - renderer: volume_renderer_default
  - signal_encoder: positional_encoding