defaults:
  - cuda: default
  - data: nerf_synthetic
  - network: instant_nerf
  - objective: nerf
  - train_params: instant_nerf
  - scene: cube
  - renderer: volume_renderer_default
  - signal_encoder: spherical_harmonics

renderer:
  num_samples_coarse: 64
  num_samples_fine: 128
  #t_near: 0.1
  #t_far: 4.1