optim:
  num_iter: 300000
  optim_type: adam
  scheduler_type: exp
  init_lr: 1e-2
  end_lr: 1e-3
  eps: 1e-15
validation:
  validate_every: 10
  num_batch: 5
log:
  epoch_btw_ckpt: 500
  epoch_btw_vis: 10
ckpt:
  path: null