strategy:
  use_hierarchical_sampling: True
optim:
  num_iter: 300000
  optim_type: adam
  scheduler_type: exp
  init_lr: 0.0005
  end_lr: 0.00005
log:
  epoch_btw_ckpt: 50
  epoch_btw_vis: 50
ckpt:
  path: null