optim:
  num_iter: 300000
  optim_type: adam
  scheduler_type: exp
  init_lr: 0.0005
  end_lr: 0.00005
  eps: 1e-8
validation:
  validate_every: 10
  num_batch: 5
log:
  epoch_btw_ckpt: 50
  epoch_btw_vis: 10
ckpt:
  path: null